apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-cluster.fullname" . }}
  labels:
    {{- include "postgres-cluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-cluster.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP