apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-cluster.fullname" . }}
  labels:
    {{- include "postgres-cluster.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres-cluster.fullname" . }}  # Needed for stable DNS like postgres-0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-cluster.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
